### ISSUE TITLE
Remove ._ files

### ISSUE THREAD

**Issue by ambalek** [michaelshmitty/SD-Installer-macos_MiSTer#2]
Even though I didn't open any SD card partitions in Finder I still somehow got a ._menu file:

```
$ find /Volumes/MiSTer_Data/ -name "._*"
/Volumes/MiSTer_Data//._MiSTer
/Volumes/MiSTer_Data//._menu.rbf
/Volumes/MiSTer_Data//#Scripts/._update.sh
```

You could do something like `find /Volumes/MiSTer_Data/ -type f -name '._*' -delete` just before ejecting.

I've also done `mdutil -i off /Volumes/MiSTer_Data` to stop Spotlight indexing

**Comment by michaelshmitty** [comment]
Good catch and thanks for the proposed solutions. I'll fix that as soon as possible.
Darn OSX littering all over the place...

**Comment by michaelshmitty** [comment]
@ambalek It seems that the ._* files only appear if you start browsing through the MiSTer_Data partition with the finder after you re-insert the SD card in your mac. At least that's what happens on my machine. When I immediately insert the SD card into the DE10-Nano after creation, there is no sign of ._ files.
Can you confirm this? If that's correct, I will close this issue as it may not seem related to the creation of the SD card.

Thanks!

**Comment by michaelshmitty** [comment]
Although stopping the Spotlight indexing may still be useful. I'll implement that.
